#!/usr/bin/bash

# wob
$WOBSOCK $XDG_RUNTIME_DIR/wob.sock >/dev/null 2>&1 &

# wallpaper
#swaybg -c '#3b05a6' & 
#swaybg -i $HOME/Pictures/linux-viola.svg &
#swaybg -i $HOME/Pictures/boat3.png >/dev/null 2>&1 &
hyprpaper >/dev/null 2>&1 &

# plugin
hyprpm reload >/dev/null 2>&1 &

# hot corners
waycorner >/dev/null 2>&1 &

# brightness
#brightnessctl set 35% >/dev/null 2>&1 &

# blu light filter 
hyprsunset  2>/dev/null &

# notifications 
mako >/dev/null 2>&1 &

# max power on desktop
#powerprofilesctl set performance >/dev/null 2>&1 &

# foot daemon
#foot --server &

# screen lock
swayidle -w timeout 500 'systemctl suspend' >/dev/null 2>&1 &

# waybar
waybar >/dev/null 2>&1 &
#waybar -c ~/.config/waybar/config-top >/dev/null 2>&1 &

# other
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY >/dev/null 2>&1 &
systemctl --user start hyprpolkitagent >/dev/null 2>&1 &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP >/dev/null 2>&1 &
# gsettings set org.gnome.desktop.interface gtk-theme 'Material-Black-Cherry' &
# gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita' &
# gsettings set org.gnome.desktop.interface icon-theme 'kora-yellow' &
# gsettings set org.gnome.desktop.interface font-name 'Jetbrains Mono 10' &
# #gsettings set org.gnome.desktop.interface text-scaling-factor 1 &
# gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' &
#gsettings set org.cinnamon.desktop.default-applications.terminal exec foot >/dev/null 2>&1 &
rm -f $WOBSOCK.wob && mkfifo $WOBSOCK.wob && tail -f $WOBSOCK.wob | wob >/dev/null 2>&1 &
