[right]

enter_command = [ "hyprctl", "dispatch", "workspace emptyn" ]
#exit_command = [ "notify-send", "exit" ]
locations = ["right"]  
size = 5  
margin = 0 
timeout_ms = 300  

[left]

enter_command = [ "hyprctl", "dispatch", "workspace e-1" ]
#exit_command = [ "notify-send", "exit" ]
locations = ["left"]  
size = 5  
margin = 0 
timeout_ms = 300  

[top_left]

enter_command = [ "fuzzel" ]
#enter_command = [ "hyprctl", "dispatch hyprexpo:expo" ]
#exit_command = [ "notify-send", "exit" ]
locations = ["top_left"]  
size = 20  
margin = 0 
timeout_ms = 150  
#color = "#FFFF0000"  

[bottom_left]

enter_command = [ ".config/scripts/fuzzel-power.sh" ]
locations = ["bottom_left"]
size = 10  
margin = 0  
timeout_ms = 100  
#color = "#FFFF0000"
